version: "3"

services:
   postgres:
      image: postgres
      container_name: postgres
      environment:
         POSTGRES_PASSWORD: postgrespw
      ports:
         - "5432:5432"

   friendify:
      image: ashennone/friendify
      container_name: friendify
      ports:
         - "8080:80"
